Drop support for Julia 1.2 because it's failing on CI
```
π: Error During Test at /home/runner/work/RealContinuedFractions.jl/RealContinuedFractions.jl/test/runtests.jl:19
  Test threw exception
  Expression: contfrac(π, 5) == ContinuedFraction([3, 7, 15, 1, 292])
  MethodError: no method matching Irrational{:π}(::Int64)
  Closest candidates are:
    Irrational{:π}(::T<:Number) where T<:Number at boot.jl:718
    Irrational{:π}() where sym at irrationals.jl:18
    Irrational{:π}(!Matched::Complex) where T<:Real at complex.jl:37
    ...
  Stacktrace:
   [1] convert(::Type{Irrational{:π}}, ::Int64) at ./number.jl:7
   [2] one(::Type{Irrational{:π}}) at ./number.jl:300
   [3] one(::Irrational{:π}) at ./number.jl:301
   [4] modf(::Irrational{:π}) at ./math.jl:766
   [5] contfrac at /home/runner/work/RealContinuedFractions.jl/RealContinuedFractions.jl/src/RealContinuedFractions.jl:48 [inlined]
   [6] contfrac(::Irrational{:π}, ::Int64) at /home/runner/work/RealContinuedFractions.jl/RealContinuedFractions.jl/src/RealContinuedFractions.jl:33
   [7] top-level scope at /home/runner/work/RealContinuedFractions.jl/RealContinuedFractions.jl/test/runtests.jl:19
   [8] top-level scope at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/Test/src/Test.jl:1113
   [9] top-level scope at /home/runner/work/RealContinuedFractions.jl/RealContinuedFractions.jl/test/runtests.jl:19
   [10] top-level scope at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/Test/src/Test.jl:1113
   [11] top-level scope at /home/runner/work/RealContinuedFractions.jl/RealContinuedFractions.jl/test/runtests.jl:11
   [12] top-level scope at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/Test/src/Test.jl:1113
   [13] top-level scope at /home/runner/work/RealContinuedFractions.jl/RealContinuedFractions.jl/test/runtests.jl:6
```